apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  creationTimestamp: null
  labels:
    app: dps-payment-service
    template: master-build-pipeline
  name: dps-payment-service
  namespace: pjztlm-tools
  resourceVersion: '1652397388'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/pjztlm-tools/buildconfigs/dps-payment-service
  uid: 344be2b2-6324-11ea-b2ea-005056832285
spec:
  completionDeadlineSeconds: 1800
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'dps-payment-service:latest'
  postCommit: {}
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 1Gi
  runPolicy: Serial
  source:
    contextDir: src/dps-payment-service
    git:
      ref: master
      uri: 'https://github.com/bcgov/jag-dps'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus:8081/repository/dps-group/'
      from:
        kind: ImageStreamTag
        name: 'java:17'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 1
