# Deploy an artifact onto Dev, Test, or Prod
name: Deploy
on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        description: App to be deployed
        type: choice
        options:
          - dps-email-poller
          - dps-email-worker
          - dps-notification-service
          - dps-payment-service
          - dps-registration-api
          - dps-validation-service
          - figaro-validation-service
          - spd-notification-worker
          - vips-notification-worker
      source_image_tag:
        required: true
        description: What is the tag that is going to be promoted?
        type: string
      environment:
        required: true
        description: What is the targeted environment?
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  promote_image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-tag-image.yml@v0.0.3
    with:
      image_stream_name: "${{ github.event.inputs.app_name }}"
      source_image_tag: "${{ github.event.inputs.source_image_tag }}"
      image_tags: "${{ github.event.inputs.environment }}"
    secrets:
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"

