name: spd-notification-worker - Build Image

on:
  push:
    branches:
      - main
    paths:
      - "src/spd-notification-worker/**"
      - ".github/workflows/dev-spd-notification-worker.yml"
  workflow_dispatch:
    branches:
      - main

jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: "src"
      profile: spd-notification-worker
    secrets:
      nexus_url: ${{ secrets.NEXUS_URL }}

  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: "src/spd-notification-worker"

  build-image:
    needs:
      - unit-test
      - app-version
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image.yml@main
    with:
      app_name: "spd-notification-worker"
      working_directory: .
