name: dps-email-worker - Build Image

on:
  push:
    branches:
      - main
    paths:
      - "src/dps-email-worker/**"
      - ".github/workflows/dev-dps-email-worker"
  workflow_dispatch:
    branches:
      - main

jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: "src"
      profile: dps-email-worker
    secrets:
      nexus_url: ${{ secrets.NEXUS_URL }}

  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: "src/dps-email-worker"

  build-image:
    needs:
      - unit-test
      - app-version
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image.yml@main
    with:
      app_name: "dps-email-worker"
      working_directory: .
    secrets:
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"
      openshift_license_plate: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}"
      docker_username: "${{ secrets.DOCKER_USERNAME }}"
      docker_password: "${{ secrets.DOCKER_PASSWORD }}"

  trivy:
    needs:
      - app-version
      - build-image
    uses: SierraSystems/reusable-workflows/.github/workflows/trivy-scan-openshift-image.yml@main
    with:
      imagestream_name: "dps-email-worker"
      image_tag: "${{ needs.app-version.outputs.app-version }}"
    secrets:
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_sa_name: "${{ secrets.OPENSHIFT_SA_PIPELINE_PASSWORD_SILVER }}"
      openshift_sa_password: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
