name: vips-notification-worker - Build Image

on:
  push:
    branches:
      - bug/vulnerability-fix
#    branches:
#      - main
#    paths:
#      - "src/vips-notification-worker/**"
  workflow_dispatch:
    branches:
      - main

jobs:
#  unit-test:
#    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@v0.0.3
#    with:
#      working_directory: "src"
#      profile: vips-notification-worker
#    secrets:
#      nexus_url: ${{ secrets.NEXUS_URL }}

  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@v0.0.3
    with:
      working_directory: "src/vips-notification-worker"

  build-image:
    needs:
#      - unit-test
      - app-version
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-and-push-image.yml@feature/allowing-multiple-tags-to-docker-build
    with:
      app_name: "vips-notification-worker"
      working_directory: .
      image_tags: "github-build"
      build_args: |-
        DPS_SERVICE_NAME=vips-notification-worker
#      image_tags: "dev,${{ needs.app-version.outputs.app-version }}"
    secrets:
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"
      openshift_license_plate: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}"
      docker_username: "${{ secrets.DOCKER_USERNAME }}"
      docker_password: "${{ secrets.DOCKER_PASSWORD }}"
  #    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@v0.0.3
#    needs:
##      - unit-test
#      - app-version
#    with:
#      build_config_name: "vips-notification-worker"
#      image_tags: "dev,${{ needs.app-version.outputs.app-version }}"
#    secrets:
#      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
#      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
#      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
#      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"

  trivy:
    needs:
      - app-version
      - build-image
    uses: SierraSystems/reusable-workflows/.github/workflows/trivy-scan-openshift-image.yml@v0.0.3
    with:
      imagestream_name: "vips-notification-worker"
      image_tag: "${{ needs.app-version.outputs.app-version }}"
    secrets:
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_sa_name: "${{ secrets.OPENSHIFT_SA_PIPELINE_PASSWORD_SILVER }}"
      openshift_sa_password: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
