name: dps-email-poller - Build Image

on:
  push:
    branches:
      - main
    paths:
      - "src/dps-email-poller/**"
      - ".github/workflows/dev-dps-email-poller.yml"
  workflow_dispatch:
    branches:
      - main
env:
  NEXUS_URL: ${{secrets.NEXUS_URL}}
jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: "src"
      profile: dps-email-poller
    secrets:
      nexus_url: ${{ secrets.NEXUS_URL }}
  
  get-app-version:
    name: Get the app-version from the POM file
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get-version.outputs.app-version }}
    defaults:
      run:
        working-directory: "src/dps-email-poller"
        #java_version: '8'

    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "java_version: 8"
          echo "working_directory: ${{ inputs.working_directory}}"

      - name: "Set up JDK 8"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Java Project Version
        id: get-version
        run: |
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout
  #app-version:
  #  uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
  #  with:
  #    working_directory: "src/dps-email-poller"

  build-image:
    needs:
      - unit-test
      #- app-version
      - get-app-version
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image.yml@main
    with:
      app_name: "dps-email-poller"
      working_directory: .
    
  trivy:
    needs:
      - unit-test
#     - app-version
    uses: Azure/container-scan@v0
    continue-on-error: true
    with:
      image-name: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}/${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools/${{inputs.imagestream_name}}:${{inputs.image_tag}}
  
  - name: Authenticate and set context
    uses: redhat-actions/oc-login@v1
    with:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
  
  - name: Login to OpenShift Container Repository
    uses: docker/login-action@v1
    with:
      registry: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Pull Image for Scanning
    run: |
      docker pull ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}/${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools/${{inputs.imagestream_name}}:${{inputs.image_tag}}  

