name: Java CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: whelk-io/maven-settings-xml-action@v20
      with:
        servers: >-
          [{
            "id":"nexus-snapshots",
            "username": "${{ secrets.NEXUS_SNAPSHOT_USERNAME }}",
            "password": "${{ secrets.NEXUS_SNAPSHOT_PASSWORD }}"
          },{
            "id":"nexus-releases",
            "username": "${{ secrets.NEXUS_RELEASES_USERNAME }}",
            "password": "${{ secrets.NEXUS_RELEASES_PASSWORD }}"
          }]

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B test --file src/pom.xml -P all
      env:
        NEXUS_URL: "${{ secrets.NEXUS_URL }}"

    #Build image for scanning
    - name: Build dps-email-worker image from Dockerfile
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
        CONTEXT: ./src/dps-email-worker
      run: |
        docker build -t dps-email-worker:${{ github.sha }} ${CONTEXT}

    #Run Vulnerability Scan usinig Trivy scanner
    - name: Run Trivy vulnerability scanner for dps-email-worker
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        image-ref: dps-email-worker:${{ github.sha }}
        format: template
        template: '@/contrib/sarif.tpl'
        output: trivy-results.sarif
        exit-code: 1
        ignore-unfixed: true
        severity: HIGH,CRITICAL
